### ISSUE TITLE
請問不帶captcha_token可以嗎？

### ISSUE THREAD

**Issue by eol3** [WayneChang65/popcat-click-it#6]
雖然有正常回應，但可以嗎？

**Comment by WayneChang65** [comment]
回應201應該可以。可以再研究一下。
如果有什麼不妥之處，也歡迎指教或送RP。感恩。

**Comment by WayneChang65** [comment]
<img width="1194" alt="截圖 2021-08-17 14 36 27" src="https://user-images.githubusercontent.com/33888917/129733764-4868cb46-4926-4005-80a7-a8693721e8e9.png">
